CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quantity INTEGER NOT NULL,
  price_unit NUMERIC NOT NULL,
  fk_product_id INTEGER NOT NULL,
  fk_order_id INTEGER NOT NULL,
  FOREIGN KEY (fk_product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (fk_order_id) REFERENCES orders(id) ON DELETE CASCADE
);
