CREATE TABLE IF NOT EXISTS store_cities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  fk_store_id INTEGER NOT NULL,
  FOREIGN KEY (fk_store_id) REFERENCES stores(id) ON DELETE CASCADE
);
