CREATE TABLE IF NOT EXISTS groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  fk_store_id INTEGER NOT NULL,
  FOREIGN KEY (fk_store_id) REFERENCES stores (id) ON DELETE CASCADE
);
