@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2FvanBtb3JlaXJhMjVAZ21haWwuY29tIiwiaWF0IjoxNzYwNjM5MjY5LCJleHAiOjE3NjMyMzEyNjl9.jfZFXbVPNktTA-Xjoz4gw47I21WtMQvTsd3_UHt27S8
### Criar categoria
POST {{baseUrl}}/complement/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Bacon Triturado",
  "description": "farofinha de bacon",
  "price": 2.00,
  "max_quantity": null,
  "image": "image",
  "fk_complement_group_id": 1,
  "fk_store_id": 2
}
### Buscar todas categoria
GET {{baseUrl}}/complement/all?fk_store_id=2
Content-Type: application/json
### Buscar categoria por ID
GET {{baseUrl}}/complement/?id=1
Content-Type: application/json
### Atualizar um categoria
PUT {{baseUrl}}/complement/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "description": "A melhor farofa de Bacon Triturado"
  }
}
### Deletar categoria
DELETE  {{baseUrl}}/complement/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}