@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2FvanBtb3JlaXJhMjVAZ21haWwuY29tIiwiaWF0IjoxNzU4NjMzMDY3LCJleHAiOjE3NjEyMjUwNjd9.6cuNBIVamW2GaHJ21WvVmRY8VjZJy0pJtJIuHEQkhQk
### Criar registro
POST {{baseUrl}}/complement-group-complements/upsert
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fk_complement_id": 1,
  "groups": [2],
  "fk_store_id": 2
}
### Buscar todos registros
GET {{baseUrl}}/complement-group-complements/all?fk_store_id=2
Content-Type: application/json
Authorization: Bearer {{token}}
### Buscar por ID
GET {{baseUrl}}/complement-group-complements?id=1
Content-Type: application/json
Authorization: Bearer {{token}}
### Atualizar registro
PUT {{baseUrl}}/complement-group-complements/update/1
Content-Type: application/json

{
  "data": {
    "fk_group_id": 3
  }
}
### Deletar registro
DELETE  {{baseUrl}}/complement-group-complements/delete/2
Content-Type: application/json