@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2FvanBtb3JlaXJhMjVAZ21haWwuY29tIiwiaWF0IjoxNzU4NjMzMDY3LCJleHAiOjE3NjEyMjUwNjd9.6cuNBIVamW2GaHJ21WvVmRY8VjZJy0pJtJIuHEQkhQk
### Criar bairro
POST {{baseUrl}}/deliveryarea/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Centro",
  "delivery_fee": 4.50,
  "delivery_time_min": 60,
  "delivery_time_max": 90,
  "fk_store_cities_id": 1,
  "fk_store_id": 2
}
### Buscar todos bairros
GET {{baseUrl}}/deliveryarea/all?fk_store_id=2
Content-Type: application/json
### Buscar bairro por ID
GET {{baseUrl}}/deliveryarea/id
Content-Type: application/json

{
  "id": 2
}
### Atualizar um bairro
PUT {{baseUrl}}/deliveryarea/update
Content-Type: application/json

{
  "id": 1,
  "data": {
    "name": "Praia da Barra"
  }
}
### Deletar bairro
DELETE  {{baseUrl}}/deliveryarea/delete
Content-Type: application/json

{
  "id": 2
}