@baseUrl = http://localhost:3000/api
### Criar horário de funcionamento 
POST {{baseUrl}}/openinghours/upsert
Content-Type: application/json

{
  "data": {
    "monday": { "opens_at": "08:00", "closes_at": "18:00" },
    "tuesday": { "opens_at": "08:00", "closes_at": "18:00" },
    "wednesday": { "opens_at": "08:00", "closes_at": "18:00" },
    "thursday": { "opens_at": "08:00", "closes_at": "18:00" },
    "friday": { "opens_at": "08:00", "closes_at": "18:00" },
    "saturday": { "opens_at": "10:00", "closes_at": "14:00" },
    "sunday": { "opens_at": null, "closes_at": null }
  },
  "fk_store_id": 1
}
### Buscar horário de funcionamento
GET {{baseUrl}}/openinghours/all
Content-Type: application/json

{
  "fk_store_id": 1
}