@baseUrl = http://localhost:3000/api
### Criar sessão
POST {{baseUrl}}/session/create
Content-Type: application/json

{
  "total_amount": 25.97,
  "delivery_method": "retirada",
  "is_scheduled": "false",
  "scheduled_for": "2025-07-08 23:29:50",
  "delivery_address": "Av. Malibu, 700 - Vila Guilhermina, Mongaguá - SP. (Próximo ao Supermercado Pão de Açucar)",
  "fk_delivery_address_id": null,
  "payment_method": "dinheiro",
  "customer_name": "El Barto",
  "customer_whatsapp": "453675456"
}
### Buscar sessão por ID
GET {{baseUrl}}/session/checkout:a3b8967c-d022-4607-9e79-205c139b6638
### Atualizar um sessão
PUT {{baseUrl}}/session/update/checkout:a3b8967c-d022-4607-9e79-205c139b6638
Content-Type: application/json

{
  "data": {
    "paid": "true",
    "status": "recebido",
    "mercadopago_pay_id": null,
    "created_at": "2025-07-14 22:23:12",
    "fk_store_delivery_area_id": null,
    "fk_user_id": null,
    "fk_store_id": 1,
    "items": [
      {
        "quantity": 1,
        "fk_product_id": 2,
        "complements": [
          {
            "fk_complement_id": 2,
            "quantity": 1
          },
          {
            "fk_complement_id": 3,
            "quantity": 1
          }
        ]
      },
      {
        "quantity": 1,
        "fk_product_id": 1,
        "complements": []
      }
    ]
  }
}
### Finalizar pedido
POST {{baseUrl}}/session/finish/checkout:a3b8967c-d022-4607-9e79-205c139b6638