@baseUrl = http://localhost:3000
@token = APP_USR-4345274821592298-010419-d6af62d1b498dfeeafcda28d39ff27ff-3110331507
### Criar categoria
POST {{baseUrl}}/admin/plans/turbo
Content-Type: application/json
Authorization: Bearer {{token}}
### Buscar todas categoria
POST {{baseUrl}}/subscriptions/subscribe
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "plan_slug": "start",
  "payer_email": "ak9585042@gmail.com",
  "card_token_id": "b7efe1813437afed96438fb42327cefc",
  "fk_store_id": 2
}
### Buscar assinatura
GET {{baseUrl}}/subscriptions/2
Content-Type: application/json
Authorization: Bearer {{token}}
### Suspender assinatura
PUT {{baseUrl}}/subscriptions/2/pause
Content-Type: application/json
Authorization: Bearer {{token}}
### Reactivar assinatura
PUT {{baseUrl}}/subscriptions/2/reactivate
Content-Type: application/json
Authorization: Bearer {{token}}
### Alterar cartão
PUT {{baseUrl}}/subscriptions/2/change-card
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "card_token_id": "fdaa92065b0b894b6fec1594c402008d"
}
### Cancelar assinatura
PUT {{baseUrl}}/subscriptions/2/cancel
Content-Type: application/json
Authorization: Bearer {{token}}
### Mudar plano
PUT {{baseUrl}}/subscriptions/2/change-plan
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "new_plan_slug": "start"
}